name: playground_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^10.2.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.6
  build_runner: ^2.10.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
